CREATE database positionControl;
use positionControl;

CREATE TABLE roles(
Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
RoleName VARCHAR(40),
RoleDescription VARCHAR(255)
);

CREATE TABLE users(
Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
FirstName VARCHAR(255),
LastName VARCHAR(255),
Username VARCHAR(255),
PaswordHash VARCHAR(255),
RoleId INT,
FOREIGN KEY (RoleId) REFERENCES roles(Id)
);

CREATE TABLE workpositions(
Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
PositionName VARCHAR(255),
PositionDescription VARCHAR(255)
);

CREATE TABLE userworkpositions(
Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
UserId INT,
PositionId INT,
Product VARCHAR(255),
AssignDate DATETIME,
FOREIGN KEY(UserId) REFERENCES users(Id),
FOREIGN KEY(PositionId) REFERENCES work_positions(Id)
);